services:
  caddy-nav.pknw1.co.uk:
    networks:
      - proxy
    image: pknw1/nav.pknw1.co.uk:latest
    container_name: caddy-nav.pknw1.co.uk
    hostname: caddy-nav.pknw1.co.uk
    environment:
      - VIRTUAL_HOST=nav.pknw1.co.uk
      - VIRTUAL_PORT=80

networks:
  proxy:
    external: true
    name: proxy
~                                                                                                                                                                                   
~                    
